"""add resource indexes

Revision ID: 288fc3fd576d
Revises: 5d2841527a9b
Create Date: 2026-06-05 12:09:43.939598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288fc3fd576d'
down_revision: Union[str, Sequence[str], None] = '5d2841527a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_resource_collection', 'resources', ['collection_id'], unique=False)
    op.create_index('idx_resource_title', 'resources', ['title'], unique=False)
    op.create_index('idx_resource_type', 'resources', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resource_type', table_name='resources')
    op.drop_index('idx_resource_title', table_name='resources')
    op.drop_index('idx_resource_collection', table_name='resources')
    # ### end Alembic commands ###
